name: bakjes_overstroming

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - gdal
  - numpy  # =1.22.3
  - pandas  # =1.4.4
  - geopandas  # =0.9.0
  - pyproj  # =2.6.1.post1
  - openpyxl # =3.0.9
  - pyarrow
  - rasterio
  - xlrd
  # - rioxarray
  - fiona

  # - pywin32
  - pip
  - pip:
    - httpx


